name: auto deploy
on:
  push:
    branches:
      - master #2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
    - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: master #2020年10月后github新建仓库默认分支改为main，注意更改

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          cache: 'npm'

      - name: 安装依赖
        run: |
          npm install

      - name: 构建
        run: |
          npm run build

      # 打包镜像推送到阿里云容器镜像服务
      - name: 构建容器镜像
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }}  ccr.ccs.tencentyun.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -t baby-shop:latest .
          docker tag baby-shop ccr.ccs.tencentyun.com/sanganqiang/baby-shop:latest
          docker push ccr.ccs.tencentyun.com/sanganqiang/baby-shop:latest
      - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ~ && sh baby-shop-deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
